spring.application.name=blog-api
#spring.profiles.active=dev

logging.level.org.mybatis=info
logging.level.org.springframework.web=info
logging.level.org.springframework.security=info
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

jwt.secret-key=123123dfdsfsdfdsdfsdfdsf123123123
jwt.access-expiration=1000000
server.port=${PORT:8090}