spring.application.name=blog-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

mybatis.configuration.map-underscore-to-camel-case=true

logging.level.org.mybatis=info
logging.level.org.springframework.web=info
logging.level.org.springframework.security=info

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

jwt.secret-key=${JWT_SECRET_KEY:dev-secret-key-not-for-production}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION:86400000}
server.port=${PORT:8090}
