spring.application.name=blog-api

logging.level.root=info
logging.level.top.blogapi=debug
logging.file.name=blog-api/log/blog-dev

logging.level.org.mybatis=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/blog
spring.datasource.hikari.username=blog
spring.datasource.hikari.password=blog123

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

jwt.secret-key=dev-secret-key-not-for-production
jwt.access-expiration=86400000

app.frontend-url=http://localhost:5174
