spring.application.name=blog-api

logging.level.root=info
logging.level.top.blogapi=debug
logging.file.name=blog-api/log/blog-dev

logging.level.org.mybatis=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.hikari.username=root
spring.datasource.hikari.password=1820

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

server.compression.enabled=false


jwt.secret-key=dev-secret-key-not-for-production
jwt.access-expiration=86400000
server.port=8090
