export { default as AppMain } from './AppMain.vue'
export { default as NavBar } from './NavBar.vue'
export { default as SideBar } from './Sidebar/index.vue'
export { default as TagsView } from './TagsView/index.vue'
export { default as Settings } from './Settings/index.vue'
export { default as Copyright } from './Copyright/index.vue'
