spring.application.name=space-api
server.port=8091


# Datasource
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/space
spring.datasource.hikari.username=space
spring.datasource.hikari.password=1820
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true

# JWT
jwt.secret-key=${JWT_SECRET_KEY:dev-secret-key-not-for-production}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION:86400000}

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

# OAuth2
#spring.security.oauth2.client.registration.google.client-id=365300137794-e1ehqplm3uf77v4j7od0mlbl4scg1t07.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=openid,email,profile
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.client-name=Google

app.frontend-url=http://localhost:5174
