spring.application.name=space-api

logging.level.org.mybatis=info
logging.level.org.springframework.web=info
logging.level.org.springframework.security=info

spring.datasource.hikari.jdbc-url=${SPRING_DATASOURCE_URL}
spring.datasource.hikari.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.hikari.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
server.port=${PORT:8090}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
